// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeIMzWUV3w1A39AZcV8NxICLlUh5SJLj4',
    appId: '1:429403777394:web:de06e0f5e50868a38d95eb',
    messagingSenderId: '429403777394',
    projectId: 'smart-school-300211',
    authDomain: 'smart-school-300211.firebaseapp.com',
    databaseURL: 'https://smart-school-300211-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-school-300211.appspot.com',
    measurementId: 'G-V07WNQQYZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYue8vjJLA8JYZGcttpmNsNw8X5ONWQHs',
    appId: '1:429403777394:android:0f7e7be3c1bbe84b8d95eb',
    messagingSenderId: '429403777394',
    projectId: 'smart-school-300211',
    databaseURL: 'https://smart-school-300211-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-school-300211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwpS2nUlJj6RMkpSuMCjD_v8y2ipULugQ',
    appId: '1:429403777394:ios:eedcbeef46e542628d95eb',
    messagingSenderId: '429403777394',
    projectId: 'smart-school-300211',
    databaseURL: 'https://smart-school-300211-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-school-300211.appspot.com',
    iosClientId: '429403777394-9v6l7jh8pnok63kt6jukd9tg4chalan9.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventarisBara',
  );
}
